<a href="https://colab.research.google.com/github/Papawadee-Mohdee/PythonDataViz2026/blob/main/Pandas_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

เว็บไซต์ข้อมูลเปิดของหน่อยงานราชการต่างๆ

https://data.go.th/

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os # os ทำการจัดการไฟล์ต่างๆ เฟิดไฟล์ ลบไฟล์ ต่างๆ

path = '/content/drive/MyDrive/Dataviz_2026_data'

In [4]:
covid_file_path = os.path.join(path,'confirmed-cases.csv')
print(covid_file_path)

/content/drive/MyDrive/Dataviz_2026_data/confirmed-cases.csv

In [5]:
# อันนี้ก็ได้ สั้นกว่า แต่ต้อง import os
a = path + '/confirmed-cases.csv'
print(a)

/content/drive/MyDrive/Dataviz_2026_data/confirmed-cases.csv

## load data to memory

In [6]:
data_covid = pd.read_csv(covid_file_path)
data_covid

/tmp/ipykernel_1835/318669438.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv(covid_file_path)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
...,...,...,...,...,...,...,...,...,...,...,...
839766,839767,12/8/2021,11/8/2021,ชาย,52.0,ปี,NaN,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839767,839768,12/8/2021,11/8/2021,ชาย,34.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839768,839769,12/8/2021,11/8/2021,ชาย,31.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839769,839770,12/8/2021,11/8/2021,ชาย,83.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN
839770,839771,12/8/2021,11/8/2021,ชาย,47.0,ปี,Thailand,กาญจนบุรี,ทัณฑสถาน/เรือนจำ,กาญจนบุรี,NaN

In [7]:
data_covid.head() #head โชว์แค่ หัวตาราง และ 5 แถวแรก

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [8]:
data_covid.shape # บอกว่ามีกี่แถวกี่หลัก

(839771, 11)

## ชี้ค่าในตาราง

#### basic

In [9]:
data_covid['province_of_onset']

0         กรุงเทพมหานคร
1         กรุงเทพมหานคร
2                นครปฐม
3         กรุงเทพมหานคร
4         กรุงเทพมหานคร
              ...
839766        กาญจนบุรี
839767        กาญจนบุรี
839768        กาญจนบุรี
839769        กาญจนบุรี
839770        กาญจนบุรี
Name: province_of_onset, Length: 839771, dtype: object

In [10]:
data_covid['province_of_onset'][4]

'กรุงเทพมหานคร'

In [11]:
data_covid['province_of_onset'][839770]

'กาญจนบุรี'

#### .iloc คือ การมองตารางเป็น array

In [12]:
data_covid.iloc[4,7]

'นนทบุรี'

## Table slicing

#### ตัดมาเฉพาะ column ที่ต้องการ

In [13]:
smaller_table = data_covid[['announce_date','province_of_onset','risk']]
smaller_table.head()

  announce_date province_of_onset                              risk
0     12/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
1     17/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
2     22/1/2020            นครปฐม  คนต่างชาติเดินทางมาจากต่างประเทศ
3     22/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
4     24/1/2020     กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ

#### ตัดเฉพาะ rows ที่ต้องการ

**แบบง่าย แต่ใช้การอะไรไม่ค่อยจะได้ (มองเป็น array แล้วตัดแบบ array)**

In [14]:
data_covid.iloc[1:5,:]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

**แบบ advanced แต่ใช้ประโยชน์ได้เยอะกว่า (ตัดแบบใช้ logic query)**

In [15]:
data_covid[data_covid['province_of_onset']=='อำนาจเจริญ']

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
972,973,26/3/2020,25/3/2020,ชาย,48.0,ปี,Thailand,อำนาจเจริญ,สถานบันเทิง,อำนาจเจริญ,เมือง
1863,1864,2/4/2020,1/4/2020,หญิง,46.0,ปี,Thailand,อำนาจเจริญ,คนไทยเดินทางกลับจากต่างประเทศ,อำนาจเจริญ,ปทุมราชวงศา
6492,6493,30/12/2020,29/12/2020,หญิง,37.0,ปี,Thailand,อำนาจเจริญ,Cluster ระยอง,อำนาจเจริญ,หัวตะพาน
7389,7390,3/1/2021,2/1/2021,หญิง,26.0,ปี,Laos,อำนาจเจริญ,สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้,อำนาจเจริญ,หัวตะพาน
31037,31038,10/4/2021,9/4/2021,ชาย,38.0,ปี,Thailand,อำนาจเจริญ,ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว,อำนาจเจริญ,เมือง
...,...,...,...,...,...,...,...,...,...,...,...
832286,832287,12/8/2021,11/8/2021,หญิง,42.0,ปี,Thailand,อำนาจเจริญ,อื่นๆ,อำนาจเจริญ,หัวตะพาน
836815,836816,12/8/2021,11/8/2021,NaN,44.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,อำนาจเจริญ,พนา
836824,836825,12/8/2021,11/8/2021,NaN,48.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,อำนาจเจริญ,พนา
836941,836942,12/8/2021,11/8/2021,NaN,49.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,อำนาจเจริญ,เมืองอำนาจเจริญ
837014,837015,12/8/2021,11/8/2021,NaN,45.0,ปี,NaN,กรุงเทพมหานคร,ระบุไม่ได้,อำนาจเจริญ,พนา

การชี้ค่าในตารางด้วย data_covid[***x***] ค่า ***x*** สามารถมีค่าที่ใส่เข้าไปได้ 2 แบบ


1.   ชื่อ column
2.   ใส่ rows ที่ต้องการ (ใส่ list ที่มี***ขนาดเท่ากับจำนวนแถว*** แล้วบอกว่าเอา แถวไหนบ้างโดยใช้ logical expression (```True```/```False```))

In [16]:
eight_rows_covid = data_covid.iloc[:8,:] # ตารางตัวอย่าง
eight_rows_covid

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
7,8,26/1/2020,NaN,หญิง,73.0,ปี,China,ประจวบคีรีขันธ์,คนต่างชาติเดินทางมาจากต่างประเทศ,ประจวบคีรีขันธ์,หัวหิน

In [17]:
eight_rows_covid[[True,False,True,True,False,True,False,False]]   #2.   ใส่ rows ที่ต้องการ

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [18]:
eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร'  #สร้าง list ของ logical expression

0     True
1     True
2    False
3     True
4     True
5     True
6     True
7    False
Name: province_of_onset, dtype: bool

In [19]:
eight_rows_covid[eight_rows_covid['province_of_onset'] == 'กรุงเทพมหานคร']  #เราเอา 2 บรรทัดบนมาบวกกัน

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
5,6,25/1/2020,NaN,หญิง,33.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
6,7,26/1/2020,NaN,หญิง,57.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [20]:
this_data = data_covid[['sex','age','province_of_onset']]

In [21]:
this_data

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[839771 rows x 3 columns]

**ผู้ป่วยหญิง**

In [37]:
female = this_data[this_data['sex']=='หญิง']
female['age']

0         61.0
1         74.0
2         73.0
4         66.0
5         33.0
          ...
839737    57.0
839738    50.0
839739    37.0
839740    24.0
839741    26.0
Name: age, Length: 399881, dtype: object

In [39]:
#เป็นการแปลงข้อมูลในคอลัมน์ 'age' ของ DataFrame female ให้เป็นตัวเลขครับ
female['age'] = pd.to_numeric(female['age'], errors='coerce')

/tmp/ipykernel_1835/2957762226.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female['age'] = pd.to_numeric(female['age'], errors='coerce')

`pd.to_numeric()`: เป็นฟังก์ชันของไลบรารี pandas ที่ใช้ในการแปลงข้อมูลให้เป็นชนิดตัวเลข

`female['age']`: คือการเลือกคอลัมน์ 'age' จาก DataFrame female

`errors='coerce'`: เป็นอาร์กิวเมนต์ที่สำคัญ หมายความว่า หากพบค่าที่ไม่สามารถแปลงเป็นตัวเลขได้ (เช่น เป็นข้อความที่ไม่ใช่ตัวเลข) ให้แทนที่ค่านั้นด้วย NaN (Not a Number) แทนที่จะแสดงข้อผิดพลาด (error)

In [40]:
sum_age = 0
N = 0
for a in female['age']:
    if not pd.isna(a) and a > 0:
        sum_age += a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง {sum_age/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง 36.16090881617699

In [ ]:
female_KK = female[female['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in female_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยหญิง ในจังหวัดขอนแก่น 41.57142857142857

**ผู้ป่วยชาย**

In [46]:
male = this_data[this_data['sex']=='ชาย']
male['age'] = pd.to_numeric(male['age'], errors='coerce')
male['age']

/tmp/ipykernel_1835/2722734749.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  male['age'] = pd.to_numeric(male['age'], errors='coerce')

3         68.0
8         63.0
10        33.0
11        61.0
12         6.0
          ...
839766    52.0
839767    34.0
839768    31.0
839769    83.0
839770    47.0
Name: age, Length: 384994, dtype: float64

In [47]:
sum_age = 0
N = 0
for a in male['age']:
    if not pd.isna(a) and a > 0:
        sum_age += a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย {sum_age/N}')

อายุเฉลี่ย ของ ผู้ป่วยชาย 34.962927021309376

In [49]:
male_KK = male[male['province_of_onset']=='ขอนแก่น']

sum = 0
N = 0
for a in male_KK['age']:

    if a > 0:
        sum += a # sum = sum + a
        N += 1

print(f'อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น {sum/N}')

อายุเฉลี่ย ของ ผู้ป่วยชาย ในจังหวัดขอนแก่น 34.057632398753896

# การจัดการ Missing

# ถึง 30.03

การจัดการ Missing Value

- ลบ record ที่เป็น missing
- แทนที่ ค่า missing ด้วยค่าที่เหมาะสม mean, default, category-unknown
- ใช้ ค่าจาก columns อื่นๆ ช่วยประมาณค่า ค่าใน column ที่หายไป (regression, deep learning, etc.)

### ลบ record (dropna)

missing = ```None``` ```NA```(not autorized) ```NaN``` (not a number)

In [26]:
this_data.shape #(12423, 3)

(839771, 3)

In [27]:
print(data_covid.shape)
print(data_covid.dropna().shape)

(839771, 11)
(599988, 11)

In [28]:
this_data.dropna().shape

(674906, 3)

In [29]:
this_data.dropna()

         sex   age province_of_onset
0       หญิง  61.0     กรุงเทพมหานคร
1       หญิง  74.0     กรุงเทพมหานคร
2       หญิง  73.0            นครปฐม
3        ชาย  68.0     กรุงเทพมหานคร
4       หญิง  66.0     กรุงเทพมหานคร
...      ...   ...               ...
839766   ชาย  52.0         กาญจนบุรี
839767   ชาย  34.0         กาญจนบุรี
839768   ชาย  31.0         กาญจนบุรี
839769   ชาย  83.0         กาญจนบุรี
839770   ชาย  47.0         กาญจนบุรี

[674906 rows x 3 columns]

In [30]:
this_data.dropna()
print(this_data.shape)

(839771, 3)

In [31]:
this_data.dropna(inplace=True)

/tmp/ipykernel_1835/3935554116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [32]:
this_data.dropna(inplace=True)
print(this_data.shape)

(674906, 3)

/tmp/ipykernel_1835/2129530393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  this_data.dropna(inplace=True)

In [33]:
this_data = data_covid[['sex','age','province_of_onset']]
this_data.shape

(839771, 3)

In [34]:
this_data.dropna().shape

(674906, 3)

In [35]:
this_data.dropna(subset=['age']).shape

(763606, 3)

### แทน missing ด้วยค่าที่เหมาะสม (```fillna```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
this_data.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
print(f'จำนวน record ก่อน drop missing ใน province {this_data.shape[0]}')
print(f'จำนวน record หลัง drop missing ใน province {this_data.dropna(subset=["province_of_onset"]).shape[0]}')

จำนวน record ก่อน drop missing ใน province 12653
จำนวน record หลัง drop missing ใน province 10662

In [ ]:
this_data_updated = this_data.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_onset':'ไม่รู้'})
this_data_updated.head()

    sex   age province_of_onset
0  หญิง  61.0     กรุงเทพมหานคร
1  หญิง  74.0     กรุงเทพมหานคร
2  หญิง  73.0            นครปฐม
3   ชาย  68.0     กรุงเทพมหานคร
4  หญิง  66.0     กรุงเทพมหานคร

In [ ]:
this_data_updated[this_data_updated['sex']=='ไม่รู้']

          sex  age province_of_onset
4391   ไม่รู้ -1.0         สมุทรสาคร
4392   ไม่รู้ -1.0         สมุทรสาคร
4393   ไม่รู้ -1.0         สมุทรสาคร
4394   ไม่รู้ -1.0         สมุทรสาคร
4395   ไม่รู้ -1.0         สมุทรสาคร
...       ...  ...               ...
12635  ไม่รู้ -1.0         สมุทรสาคร
12636  ไม่รู้ -1.0         สมุทรสาคร
12637  ไม่รู้ -1.0         สมุทรสาคร
12638  ไม่รู้ -1.0         สมุทรสาคร
12639  ไม่รู้ -1.0         สมุทรสาคร

[2502 rows x 3 columns]

In [ ]:
this_data_updated['province_of_onset']=='ไม่รู้'

0        False
1        False
2        False
3        False
4        False
         ...
12648    False
12649    False
12650    False
12651    False
12652    False
Name: province_of_onset, Length: 12653, dtype: bool

In [ ]:
data_covid[this_data_updated['province_of_onset']=='ไม่รู้']

         No.  ...                                         risk
414      415  ...                                      สนามมวย
529      530  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
555      556  ...                                      สนามมวย
576      577  ...                                      สนามมวย
588      589  ...                         อยู่ระหว่างการสอบสวน
...      ...  ...                                          ...
12405  12406  ...                            Cluster สมุทรสาคร
12406  12407  ...                            Cluster สมุทรสาคร
12407  12408  ...                            Cluster สมุทรสาคร
12408  12409  ...                            Cluster สมุทรสาคร
12409  12410  ...                            Cluster สมุทรสาคร

[1991 rows x 10 columns]

In [ ]:
this_data_updated_2 = this_data.fillna(value={'province_of_onset':'ไม่รู้'})

In [ ]:
this_data_updated_2[this_data_updated['sex']=='ไม่รู้']

       sex  age province_of_onset
4391   NaN  NaN         สมุทรสาคร
4392   NaN  NaN         สมุทรสาคร
4393   NaN  NaN         สมุทรสาคร
4394   NaN  NaN         สมุทรสาคร
4395   NaN  NaN         สมุทรสาคร
...    ...  ...               ...
12635  NaN  NaN         สมุทรสาคร
12636  NaN  NaN         สมุทรสาคร
12637  NaN  NaN         สมุทรสาคร
12638  NaN  NaN         สมุทรสาคร
12639  NaN  NaN         สมุทรสาคร

[2502 rows x 3 columns]

### การวนลูป record ในตาราง  (```.iterrows```)

In [ ]:
this_data = data_covid[['sex','age','province_of_onset']]

In [ ]:
for each_row in this_data.iterrows():
    # print(each_row)
    # print(each_row[1])
    if (each_row[1]['age'] == 20) and (each_row[1]['province_of_onset'] == 'ขอนแก่น'):
        print(each_row)

(9334, sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object)

### การวนลูป แบบมองตารางแพนด้าส์(pandas dataframe) เป็น numpy array  (```.iloc```)

In [ ]:
for each_row in range(this_data.shape[0]):
    if (this_data.iloc[each_row,1] == 20) and (this_data.iloc[each_row,2] == 'ขอนแก่น'):  #each_row คือ ตัวเลข
        print(each_row)
        print(this_data.iloc[each_row,:])

9334
sex                      ชาย
age                       20
province_of_onset    ขอนแก่น
Name: 9334, dtype: object

## Quiz ตัดตารางออกมาเฉพาะปี 2021 ```announce_date``` ในปี 2021

**Hint**
*   วนลูปหา index ของปี 2021
*   ตัดตารางมาเฉพาะ ปี 2021

In [ ]:
TF=list()
for each_row in data_covid.iterrows():
    if each_row[1]['announce_date'].split('/')[2] == '2021':
        TF.append(True)
    else:
        TF.append(False)

data_covid[TF].head()

       No.  ...                                               risk
6884  6885  ...                                  Cluster สมุทรสาคร
6885  6886  ...                                      Cluster ระยอง
6886  6887  ...                                        สถานบันเทิง
6887  6888  ...                                  Cluster สมุทรสาคร
6888  6889  ...  อาชีพเสี่ยง เช่น ทำงานในสถานที่แออัด หรือทำงาน...

[5 rows x 10 columns]

# Function ตัวช่วยใน pandas

### ```.describe()``` คำนวณค่าทางสถิติของข้อมูลที่เป็นตัวเลข

In [ ]:
data_covid.describe()

                No.          age
count  12653.000000  8881.000000
mean    6327.000000    38.054748
std     3652.750813    15.125178
min        1.000000     0.100000
25%     3164.000000    27.000000
50%     6327.000000    36.000000
75%     9490.000000    48.000000
max    12653.000000    97.000000

### ```.mean()``` คำนวณค่าเฉลี่ยของข้อมูลโดยไม่สนใจ missing

In [ ]:
data_covid[data_covid['sex']=='ชาย']['age'].mean()

39.46076940331987

### ```.isnull()```

In [ ]:
data_covid.isnull()

         No.  announce_date  ...  district_of_onset   risk
0      False          False  ...               True  False
1      False          False  ...               True  False
2      False          False  ...              False  False
3      False          False  ...               True  False
4      False          False  ...               True  False
...      ...            ...  ...                ...    ...
12648  False          False  ...              False  False
12649  False          False  ...              False  False
12650  False          False  ...              False  False
12651  False          False  ...              False  False
12652  False          False  ...              False  False

[12653 rows x 10 columns]

# next
*   .describe
*   .mean
*   HW วนลูป missing .isnull
*   ต่อตารางแกน X แกน y
*   .groupby
*   save table